services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
      - SQLSERVR_MEM_LIMIT=1500
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  appointment-service:
    image: appointment-service:latest
    container_name: appointment_api
    build:
      context: .
      dockerfile: AppointmentService/AppointmentService.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=AppointmentDB;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - Jwt__Secret=ThisIsMySuperSecretKeyForJwtTokenDoNotShareIt12345
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - db
    restart: always

  gateway:
    image: clinic-gateway:latest
    container_name: clinic_gateway
    build:
      context: .
      dockerfile: ClinicGateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Secret=ThisIsMySuperSecretKeyForJwtTokenDoNotShareIt12345
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - appointment-service
    restart: always

  frontend:
    image: clinic-frontend:latest
    container_name: clinic_web
    build:
      context: ./ClinicFrontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    restart: always

  # pharmacy-service:
  #   image: pharmacy-service:latest
  #   container_name: pharmacy_api
  #   build:
  #     context: ./PharmacyService
  #     dockerfile: PharmacyBillingService/Dockerfile
  #   ports:
  #     - "5001:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Server=db,1433;Database=PharmacyDB;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;MultipleActiveResultSets=true
  #     - JwtSettings__SecretKey=ThisIsMySuperSecretKeyForJwtTokenDoNotShareIt12345
  #     - JwtSettings__Issuer=PharmacyBillingService
  #     - JwtSettings__Audience=MicroservicesClient
  #     - TZ=Asia/Ho_Chi_Minh
  #   depends_on:
  #     - db
  #   restart: always

volumes:
  mssql_data:
